import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "../index.css";
export const metadata = {
     title: "Next.js",
     description: "Generated by Next.js",
};

export default function RootLayout({
     children,
}: {
     children: React.ReactNode;
}) {
     return (
          <html lang="en">
               <body>
                    <nav>
                         <Navbar />
                    </nav>
                    {children}
                    <footer>
                         <Footer />
                    </footer>
               </body>
          </html>
     );
}
